/**
 * LSP 服务器定义
 * 
 * 支持 30+ 语言服务器
 */

import { LSPServerInfo } from "./types.js";

export const servers: Record<string, LSPServerInfo> = {
  typescript: {
    id: "typescript",
    name: "TypeScript",
    extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"],
    downloadType: "npm",
    binaryName: "typescript-language-server",
    rootMarkers: ["package.json", "tsconfig.json"],
    requiresSystemBinary: true,
    defaultArgs: ["--stdio"],
  },
  python: {
    id: "python",
    name: "Python",
    extensions: [".py", ".pyi", ".pyw"],
    downloadType: "npm",
    binaryName: "pyright-langserver",
    rootMarkers: ["pyproject.toml", "requirements.txt", "setup.py", "Pipfile"],
  },
  java: {
    id: "java",
    name: "Java",
    extensions: [".java"],
    downloadUrl:
      "https://www.eclipse.org/downloads/download.php?file=/jdtls/snapshots/jdt-language-server-latest.tar.gz",
    downloadType: "github",
    binaryName: "jdtls",
    rootMarkers: ["pom.xml", "build.gradle", "build.gradle.kts", ".project"],
    requiresJava: true,
    minJavaVersion: 21,
  },
  cpp: {
    id: "cpp",
    name: "C++",
    extensions: [".c", ".cpp", ".cc", ".cxx", ".h", ".hpp", ".hh", ".hxx"],
    downloadUrl: "https://github.com/clangd/clangd/releases/latest",
    downloadType: "github",
    binaryName: "clangd",
    rootMarkers: ["compile_commands.json", "CMakeLists.txt", ".clangd"],
  },
  rust: {
    id: "rust",
    name: "Rust",
    extensions: [".rs"],
    binaryName: "rust-analyzer",
    rootMarkers: ["Cargo.toml", "Cargo.lock"],
    requiresSystemBinary: true,
  },
  go: {
    id: "go",
    name: "Go",
    extensions: [".go"],
    downloadType: "go",
    binaryName: "gopls",
    rootMarkers: ["go.mod", "go.sum"],
  },
  html: {
    id: "html",
    name: "HTML",
    extensions: [".html", ".htm"],
    downloadType: "npm",
    binaryName: "vscode-html-languageserver",
    rootMarkers: ["package.json"],
  },
  css: {
    id: "css",
    name: "CSS",
    extensions: [".css", ".scss", ".sass", ".less"],
    downloadType: "npm",
    binaryName: "vscode-css-languageserver",
    rootMarkers: ["package.json"],
  },
  json: {
    id: "json",
    name: "JSON",
    extensions: [".json", ".jsonc", ".arcconfig"],
    downloadType: "npm",
    binaryName: "vscode-json-languageserver",
    rootMarkers: ["package.json"],
  },
  yaml: {
    id: "yaml",
    name: "YAML",
    extensions: [".yaml", ".yml"],
    downloadType: "npm",
    binaryName: "yaml-language-server",
    rootMarkers: ["package.json"],
  },
  markdown: {
    id: "markdown",
    name: "Markdown",
    extensions: [".md", ".markdown", ".mdown", ".mkd"],
    downloadType: "npm",
    binaryName: "remark-language-server",
    rootMarkers: ["package.json"],
  },
  php: {
    id: "php",
    name: "PHP",
    extensions: [".php", ".phtml"],
    downloadUrl: "https://github.com/felixfbecker/php-language-server/releases/latest",
    downloadType: "github",
    binaryName: "php-language-server",
    rootMarkers: ["composer.json"],
  },
  ruby: {
    id: "ruby",
    name: "Ruby",
    extensions: [".rb", ".rake", ".gemspec", ".ru"],
    downloadType: "gem",
    binaryName: "solargraph",
    rootMarkers: ["Gemfile", ".ruby-version"],
  },
  csharp: {
    id: "csharp",
    name: "C#",
    extensions: [".cs", ".csx"],
    downloadType: "dotnet",
    binaryName: "OmniSharp",
    rootMarkers: ["*.sln", "*.csproj"],
  },
  vb: {
    id: "vb",
    name: "Visual Basic",
    extensions: [".vb", ".vbs"],
    downloadType: "dotnet",
    binaryName: "OmniSharp",
    rootMarkers: ["*.sln", "*.vbproj"],
  },
  lua: {
    id: "lua",
    name: "Lua",
    extensions: [".lua"],
    downloadType: "npm",
    binaryName: "lua-language-server",
    rootMarkers: [".lua-version"],
  },
  swift: {
    id: "swift",
    name: "Swift",
    extensions: [".swift"],
    downloadUrl: "https://github.com/sourcekit-lsp/sourcekit-lsp/releases/latest",
    downloadType: "github",
    binaryName: "sourcekit-lsp",
    rootMarkers: ["Package.swift"],
  },
  kotlin: {
    id: "kotlin",
    name: "Kotlin",
    extensions: [".kt", ".kts"],
    downloadUrl: "https://github.com/fwcd/kotlin-language-server/releases/latest",
    downloadType: "github",
    binaryName: "kotlin-language-server",
    rootMarkers: ["build.gradle.kts", "settings.gradle.kts"],
  },
  scala: {
    id: "scala",
    name: "Scala",
    extensions: [".scala", ".sc"],
    downloadUrl: "https://github.com/scalameta/metals/releases/latest",
    downloadType: "github",
    binaryName: "metals",
    rootMarkers: ["build.sbt", "build.sc"],
  },
  haskell: {
    id: "haskell",
    name: "Haskell",
    extensions: [".hs", ".lhs", ".hsig"],
    downloadType: "npm",
    binaryName: "haskell-language-server",
    rootMarkers: ["*.cabal", "stack.yaml", "package.yaml"],
  },
  elixir: {
    id: "elixir",
    name: "Elixir",
    extensions: [".ex", ".exs"],
    downloadType: "npm",
    binaryName: "elixir-ls",
    rootMarkers: ["mix.exs", "mix.lock"],
  },
  erlang: {
    id: "erlang",
    name: "Erlang",
    extensions: [".erl", ".hrl"],
    downloadUrl: "https://github.com/erlang-ls/erlang_ls/releases/latest",
    downloadType: "github",
    binaryName: "erlang_ls",
    rootMarkers: ["rebar.config", "erlang.mk"],
  },
  ocaml: {
    id: "ocaml",
    name: "OCaml",
    extensions: [".ml", ".mli", ".mll", ".mly"],
    downloadUrl: "https://github.com/ocaml/ocaml-lsp/releases/latest",
    downloadType: "github",
    binaryName: "ocamllsp",
    rootMarkers: ["*.opam", "dune-project"],
  },
  vue: {
    id: "vue",
    name: "Vue",
    extensions: [".vue"],
    downloadType: "npm",
    binaryName: "vue-language-server",
    rootMarkers: ["package.json"],
  },
  svelte: {
    id: "svelte",
    name: "Svelte",
    extensions: [".svelte"],
    downloadType: "npm",
    binaryName: "svelte-language-server",
    rootMarkers: ["package.json"],
  },
  angular: {
    id: "angular",
    name: "Angular",
    extensions: [".ts", ".html"],
    downloadType: "npm",
    binaryName: "@angular/language-server",
    rootMarkers: ["angular.json"],
  },
  powershell: {
    id: "powershell",
    name: "PowerShell",
    extensions: [".ps1", ".psm1", ".psd1", ".ps1xml"],
    downloadType: "npm",
    binaryName: "powershell-language-server",
    rootMarkers: ["*.psd1"],
  },
  dockerfile: {
    id: "dockerfile",
    name: "Dockerfile",
    extensions: ["Dockerfile", ".dockerfile"],
    downloadType: "npm",
    binaryName: "dockerfile-language-server",
    rootMarkers: ["Dockerfile", ".dockerignore"],
  },
  terraform: {
    id: "terraform",
    name: "Terraform",
    extensions: [".tf", ".tfvars", ".hcl"],
    downloadType: "npm",
    binaryName: "terraform-ls",
    rootMarkers: ["*.tf", ".terraform"],
  },
  graphql: {
    id: "graphql",
    name: "GraphQL",
    extensions: [".graphql", ".gql"],
    downloadType: "npm",
    binaryName: "graphql-language-service-cli",
    rootMarkers: ["graphql.config.js", ".graphqlrc*"],
  },
  vim: {
    id: "vim",
    name: "Vim",
    extensions: [".vim", ".nvim"],
    downloadType: "npm",
    binaryName: "vim-language-server",
    rootMarkers: [],
  },
  latex: {
    id: "latex",
    name: "LaTeX",
    extensions: [".tex", ".bib", ".cls", ".sty"],
    downloadType: "npm",
    binaryName: "texlab",
    rootMarkers: ["*.tex"],
  },
  julia: {
    id: "julia",
    name: "Julia",
    extensions: [".jl"],
    downloadUrl: "https://github.com/julia-vscode/LanguageServer.jl/releases/latest",
    downloadType: "github",
    binaryName: "julia-language-server",
    rootMarkers: ["Project.toml"],
  },
  r: {
    id: "r",
    name: "R",
    extensions: [".r", ".R", ".rda", ".rds"],
    downloadType: "npm",
    binaryName: "r-languageserver",
    rootMarkers: [".Rprofile"],
  },
};

export function getServer(id: string): LSPServerInfo | undefined {
  return servers[id];
}

export function getAllServers(): LSPServerInfo[] {
  return Object.values(servers);
}

export function getServersByExtension(ext: string): LSPServerInfo[] {
  return Object.values(servers).filter((s) =>
    s.extensions.includes(ext)
  );
}
